// Main sitemap: all static + content pages + programmatic state
// landing pages. Individual job pages live in /jobs/sitemap.xml
// (generated by app/jobs/sitemap.ts) to keep this file fast and
// cacheable.

import type { MetadataRoute } from "next";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { US_STATES } from "@/lib/us-states";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://hirecre.com";

// Static routes that exist in app/ and are indexable.
// Weights are relative — the landing page gets priority 1.0 and the
// rest tier down by importance.
const STATIC_ROUTES: Array<{
  path: string;
  priority: number;
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
}> = [
  { path: "/", priority: 1.0, changeFrequency: "daily" },
  { path: "/board", priority: 0.9, changeFrequency: "hourly" },
  { path: "/jobs/in", priority: 0.8, changeFrequency: "daily" },
  { path: "/interview-prep", priority: 0.9, changeFrequency: "weekly" },
  { path: "/resources", priority: 0.7, changeFrequency: "weekly" },
  { path: "/commercial-real-estate-career-guide", priority: 0.8, changeFrequency: "monthly" },
  { path: "/commercial-real-estate-salary-guide", priority: 0.8, changeFrequency: "monthly" },
  { path: "/cre-interview-questions", priority: 0.8, changeFrequency: "monthly" },
  { path: "/acquisitions-analyst-real-estate", priority: 0.8, changeFrequency: "monthly" },
  { path: "/about", priority: 0.4, changeFrequency: "yearly" },
  { path: "/contact", priority: 0.4, changeFrequency: "yearly" },
  { path: "/privacy", priority: 0.2, changeFrequency: "yearly" },
  { path: "/terms", priority: 0.2, changeFrequency: "yearly" },
];

// Interview prep concept pages — each is a long-tail SEO target
// like "dscr vs debt yield" or "equity waterfall basics".
const INTERVIEW_PREP_SLUGS = [
  "acquisitions-interview-questions",
  "asset-management-interview-questions",
  "bridge-lending-questions",
  "broker-questions",
  "brokerage-interview-questions",
  "cap-rate-explained",
  "common-mistakes",
  "construction-budget-101",
  "credit-memo-template",
  "debt-yield-explained",
  "development-interview-questions",
  "development-returns-yoc",
  "dscr-minimums",
  "dscr-vs-debt-yield",
  "equity-returns-101",
  "equity-waterfall-basics",
  "exit-underwriting",
  "explain-irr-interview",
  "leasing-interview-questions",
  "loan-sizing-cheat-sheet",
  "loan-to-cost-ltc",
  "mini-case-practice",
  "preferred-return",
  "promote-structure",
  "property-management-interview-questions",
  "rent-roll-t12-deep-dive",
  "repe-interview-questions",
  "risk-and-structure",
  "sitemap",
  "sponsor-risk-analysis",
  "underwriting-walkthrough",
];

// Pull the most recent job touch time so the board page + state
// pages carry an accurate lastModified timestamp.
async function getBoardLastMod(): Promise<Date> {
  try {
    const { data } = await supabaseAdmin()
      .from("jobs")
      .select("last_seen_at")
      .eq("is_active", true)
      .order("last_seen_at", { ascending: false })
      .limit(1);
    const ts = data?.[0]?.last_seen_at;
    return ts ? new Date(ts) : new Date();
  } catch {
    return new Date();
  }
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  const boardLastMod = await getBoardLastMod();

  const isLiveBoardPage = (p: string) =>
    p === "/board" || p === "/jobs/in" || p === "/";

  const staticEntries: MetadataRoute.Sitemap = STATIC_ROUTES.map((r) => ({
    url: `${SITE_URL}${r.path}`,
    lastModified: isLiveBoardPage(r.path) ? boardLastMod : now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));

  const prepEntries: MetadataRoute.Sitemap = INTERVIEW_PREP_SLUGS.map((s) => ({
    url: `${SITE_URL}/interview-prep/${s}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  const stateEntries: MetadataRoute.Sitemap = US_STATES.map((s) => ({
    url: `${SITE_URL}/jobs/in/${s.slug}`,
    lastModified: boardLastMod,
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  return [...staticEntries, ...prepEntries, ...stateEntries];
}
